version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: vaulttrack_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vaulttrack
      POSTGRES_PASSWORD: vaulttrack123
      POSTGRES_DB: vaulttrack
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: