version: 2.1

jobs:
  test:
    docker:
      - image: node:22
    steps:
      - checkout
      - run:
          name: Instalar dependências
          command: npm install
      - run:
          name: Rodar testes
          command: npm test

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Fazer Deploy para Render
          command: |
            curl -X POST "https://api.render.com/deploy/srv-xxxxxxxxxx?key=$RENDER_API_KEY"

workflows:
  version: 2
  ci_cd:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
